version: '3.8'

services:
   fit-control-app:
      build:
         context: .
         dockerfile: Dockerfile.dev
      working_dir: /app
      volumes:
         - ./:/app
         - /app/node_modules
      ports:
         - '3010:3010'
      env_file:
         - .env
      depends_on:
         - redis
      networks:
         - fit-control-network

   redis:
      image: redis:alpine
      ports:
         - '6379:6379'
      networks:
         - fit-control-network

networks:
   fit-control-network:
      driver: bridge

volumes:
   postgres_data:
